version: '3.8'
services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql

    bot:
        build: .
        restart: always
        environment:
            DB_HOST: db
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_PORT: ${DB_PORT}
            VERSION: ${VERSION}
            BOT_NAME: ${BOT_NAME}
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            DISCORD_BOT_PREFIX: ${DISCORD_BOT_PREFIX}
            DISCORD_BOT_APP_ID: ${DISCORD_BOT_APP_ID}
            TENOR_API_KEY: ${TENOR_API_KEY}
        volumes:
            - ./src:/app/src
            - ./logs:/app/logs
        depends_on:
            - db